### ISSUE TITLE
[WebFramework] Version

### ISSUE THREAD

**Issue by bram-nijenkamp** [olaeld/DFUnit#4]
Hello olaeld,

Do you have or are you working on a version for web based classes.
I've been trying for a bit but the compiler clearly doesn't like it that much?

Sincerely,
FrozenSource

**Comment by olaeld** [comment]
Hello FrozenSource,

Really happy to see that you are considering using a test framework for DataFlex. DFUnit is a general purpose testing library for DataFlex, and you can use it for writing any type of test you want.

I'm not sure exactly what you are trying to do, and what kind of problems you have encountered. If you can provide a tiny sample workspace demonstrating what you are trying to do, that should make it easier to diagnoze.

You can post here on GitHub, but I actually recommend using the [DataFlex forums](https://support.dataaccess.com/forums/). In any case, I will try to help you move ahead.

**Comment by bram-nijenkamp** [comment]
The problem is that the testrunner is running as a windows application. But both frameworks have functions and defines that are the same. Thus when using web components within the testrunner, it won't compile.

**Comment by olaeld** [comment]
I see. Can you give an example of a test that fails to compile?

I guess this problem can arise if you want to test a method in a subclass of a web framework class. When you include the web framework class in the Windows project, you get a compile error because of duplicate definitions. It is possible to circumnavigate this problem by architecting the methods you want to test in such a way that they are defined in separate classes that are not inheriting from the web framework classes (and then use composition instead of inheritance in your application). This may or may not be desirable from your point of view, but it could be a possibility.

If you can provide a specific example of how this problem arises, I can hopefully provide more specific help.

**Comment by bram-nijenkamp** [comment]
Well that is exactly the problem, I'l try putting all functions etc. in another class.

**Comment by olaeld** [comment]
Ok. I'm interested to hear how it worked out.
